# Generated by Django 3.1.3 on 2020-11-24 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['-start_time']},
        ),
    ]
